# Stance Detection

In [61]:
import pandas as pd
import nltk
import numpy as np
import preprocessing, feature_engineering, helpers
import importlib
from collections import Counter
from sklearn.metrics import confusion_matrix
import score
from sklearn.preprocessing import StandardScaler, LabelEncoder
import scipy
import matplotlib.pyplot as plt

In [62]:
importlib.reload(preprocessing)
importlib.reload(feature_engineering)
importlib.reload(helpers)
preprocess = preprocessing.Preprocessing()

In [63]:
train_stances = pd.read_csv("fn_data/train_stances.csv")
train_stances = train_stances.loc[lambda x: x.Stance != "unrelated"]
print(train_stances.shape)
train_stances.head()

(13427, 3)


Headline  Body ID    Stance
1   Hundreds of Palestinians flee floods in Gaza a...      158     agree
4   Spider burrowed through tourist's stomach and ...     1923  disagree
5   'Nasa Confirms Earth Will Experience 6 Days of...      154     agree
8   Banksy 'Arrested & Real Identity Revealed' Is ...     1739     agree
10                                     Gateway Pundit     2327   discuss

In [64]:
train_bodies = pd.read_csv("fn_data/train_bodies.csv")
print(train_bodies.shape)
train_bodies.head()

(1683, 2)


Body ID                                        articleBody
0        0  A small meteorite crashed into a wooded area i...
1        4  Last week we hinted at what was to come as Ebo...
2        5  (NEWSER) – Wonder how long a Quarter Pounder w...
3        6  Posting photos of a gun-toting child online, I...
4        7  At least 25 suspected Boko Haram insurgents we...

In [65]:
stances_tr, stances_val = preprocess.train_test_split(train_bodies, train_stances)
stances_tr.shape, stances_val.shape

((10696, 3), (2731, 3))

In [66]:
ct = Counter(stances_val['Stance'])
print(ct.most_common(1)[0][1]/len(list(stances_val["Stance"])))

0.6883925302087147


In [67]:
glove_dict = preprocess.get_glove_dict("glove.6B.50d")

In [71]:
list(stances_tr.iloc[14,:])

["No, it's not Tiger Woods selling an island in Lake Mälaren", 965, 'disagree']

In [14]:
def process_body_stance(body):
    

def process_bodies_stance()

KeyError: 'Agree'

In [72]:
preprocess.get_clean_tokens("No, it's not Tiger Woods selling an island in Lake Mälaren", False)

['no', 'not', 'tiger', 'wood', 'selling', 'island', 'lake', 'mälaren']

In [33]:
set(feature_extraction.text.ENGLISH_STOP_WORDS).difference(set(stopwords.words('english')))

{'across',
 'afterwards',
 'almost',
 'alone',
 'along',
 'already',
 'also',
 'although',
 'always',
 'among',
 'amongst',
 'amoungst',
 'amount',
 'another',
 'anyhow',
 'anyone',
 'anything',
 'anyway',
 'anywhere',
 'around',
 'back',
 'became',
 'become',
 'becomes',
 'becoming',
 'beforehand',
 'behind',
 'beside',
 'besides',
 'beyond',
 'bill',
 'bottom',
 'call',
 'cannot',
 'cant',
 'co',
 'con',
 'could',
 'couldnt',
 'cry',
 'de',
 'describe',
 'detail',
 'done',
 'due',
 'eg',
 'eight',
 'either',
 'eleven',
 'else',
 'elsewhere',
 'empty',
 'enough',
 'etc',
 'even',
 'ever',
 'every',
 'everyone',
 'everything',
 'everywhere',
 'except',
 'fifteen',
 'fifty',
 'fill',
 'find',
 'fire',
 'first',
 'five',
 'former',
 'formerly',
 'forty',
 'found',
 'four',
 'front',
 'full',
 'get',
 'give',
 'go',
 'hasnt',
 'hence',
 'hereafter',
 'hereby',
 'herein',
 'hereupon',
 'however',
 'hundred',
 'ie',
 'inc',
 'indeed',
 'interest',
 'keep',
 'last',
 'latter',
 'latterly',
 

In [60]:
true_label = val_df.iloc[:,-1]
prediction = model.predict(val_df.iloc[:,:-1])
matrix = confusion_matrix(true_label,prediction)
print('confusion matrix: \n{}\n'.format(matrix))

confusion matrix: 
[[  41    0  681]
 [   4    0  196]
 [  38    0 1754]]



In [61]:
#use FNC scorer to generate score report
label_prediction = encoder.inverse_transform(prediction)
label_actual = pd.DataFrame(stances_val)['Stance']
score.report_score(label_actual, label_prediction)

-------------------------------------------------------------
|           |   agree   | disagree  |  discuss  | unrelated |
-------------------------------------------------------------
|   agree   |    41     |     0     |    681    |     0     |
-------------------------------------------------------------
| disagree  |     4     |     0     |    196    |     0     |
-------------------------------------------------------------
|  discuss  |    38     |     0     |   1754    |     0     |
-------------------------------------------------------------
| unrelated |     0     |     0     |     0     |     0     |
-------------------------------------------------------------
Score: 2024.75 out of 2714.0	(74.6039056742815%)


/Users/dannyyang/Library/Python/3.6/lib/python/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


74.6039056742815